export const moviesData = [
    {
        emotionTags: ["slasher", "time travel"],
        isTerrifying: false,
        image: "totally-killer.webp",
        alt: "totally killer movie poster",
    },
    {
        emotionTags: ["time travel"],
        isTerrifying: false,
        image: "triangle.webp",
        alt: "triangle",
    },
    {
        emotionTags: ["slasher"],
        isTerrifying: false,
        image: "friday-the-thirteenth.jpg",
        alt: "friday the thirteenth",
    },
    {
        emotionTags: ["slasher"],
        isTerrifying: false,
        image: "nightmare-on-elm-street.jpg",
        alt: "nightmare on elm street",
    },
    {
        emotionTags: ["slasher", "time travel"],
        isTerrifying: false,
        image: "happy-death-day.webp",
        alt: "happy death day movie poster",
    },
     {
        emotionTags: ["body horror"],
        isTerrifying: false,
        image: "the-fly.webp",
        alt: "the fly movie poster",
    },
    {
        emotionTags: ["body horror"],
        isTerrifying: true,
        image: "in-my-mothers-skin.webp",
        alt: "in my mother's skin movie poster",
    },
    {
        emotionTags: ["body horror", "blood tests"],
        isTerrifying: true,
        image: "alien.webp",
        alt: "alien movie poster",
    },
    {
        emotionTags: ["blood tests", "body horror"],
        isTerrifying: false,
        image: "the-thing.webp",
        alt: "the thing poster",
    },
    {
        emotionTags: ["blood tests"],
        isTerrifying: false,
        image: "interview-with-the-vampire.webp",
        alt: "interview with the vampire poster",
    },
    {
        emotionTags: ["blood tests"],
        isTerrifying: false,
        image: "interview-with-the-vampire.webp",
        alt: "interview with the vampire poster",
    },
    {
        emotionTags: ["don't look up"],
        isTerrifying: false,
        image: "no-one-will-save-you.webp",
        alt: "no one will save you movie poster",
    },
    {
        emotionTags: ["don't look up"],
        isTerrifying: false,
        image: "nope.jpg",
        alt: "nope",
    },
    {
        emotionTags: ["don't look up"],
        isTerrifying: false,
        image: "the-fourth-kind.jpeg",
        alt: "the fourth kind",
    },
    {
        emotionTags: ["hey what's up with your neighbor?"],
        isTerrifying: false,
        image: "disturbia.jpg",
        alt: "disturbia movie poster",
    },
    {
        emotionTags: ["hey what's up with your neighbor?"],
        isTerrifying: true,
        image: "funny-games.jpeg",
        alt: "funny games",
    },
    {
        emotionTags: ["hey what's up with your neighbor?"],
        isTerrifying: true,
        image: "the-strangers.jpeg",
        alt: "the strangers",
    },
     {
        emotionTags: ["blood tests"],
        isTerrifying: false,
        image: "house-of-darkness.jpg",
        alt: "house of darkness movie poster",
    },
    {
        emotionTags: ["blood tests"],
        isTerrifying: false,
        image: "let-the-right-one-in.webp",
        alt: "let the right one in movie poster",
    },
    {
        emotionTags: ["blood tests"],
        isTerrifying: false,
        image: "30-days-of-night.webp",
        alt: "house of darkness movie poster",
    },
    {
        emotionTags: ["body horror"],
        isTerrifying: false,
        image: "the-blob.webp",
        alt: "the blob",
    },
    {
        emotionTags: ["body horror"],
        isTerrifying: true,
        image: "raw.webp",
        alt: "raw",
    },
    {
        emotionTags: ["body horror"],
        isTerrifying: false,
        image: "malignant.webp",
        alt: "malignant",
    },
    {
        emotionTags: ["body horror"],
        isTerrifying: false,
        image: "30-days-of-night.webp",
        alt: "30 days of night",
    },
    {
        emotionTags: ["body horror"],
        isTerrifying: false,
        image: "the-autopsy-of-jane-doe.jpg",
        alt: "the autopsy of jane doe",
    },
    {
        emotionTags: ["It's a classic"],
        isTerrifying: false,
        image: "evil-dead.jpg",
        alt: "evil dead",
    },
    {
        emotionTags: ["It's a classic"],
        isTerrifying: false,
        image: "rosemarys-baby.jpeg",
        alt: "rosemary's baby",
    },
    {
        emotionTags: ["It's a classic"],
        isTerrifying: true,
        image: "the-exorcist.jpeg",
        alt: "the exorcist",
    },
    {
        emotionTags: ["It's a classic"],
        isTerrifying: false,
        image: "the-omen.webp",
        alt: "the omen",
    },
    {
        emotionTags: ["It's a classic"],
        isTerrifying: true,
        image: "the-shining.webp",
        alt: "the shining",
    },
    {
        emotionTags: ["zombies"],
        isTerrifying: true,
        image: "train-to-busan.webp",
        alt: "train to busan",
    },
    {
        emotionTags: ["zombies"],
        isTerrifying: false,
        image: "shaun-of-the-dead.webp",
        alt: "shaun of the dead",
    },
]
